# Generated by Django 3.2.19 on 2023-09-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('amount', models.IntegerField()),
                ('buy_price', models.FloatField()),
                ('time_buy', models.DateTimeField()),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
