# Generated by Django 3.2.19 on 2023-09-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Barang',
            new_name='Transaksi',
        ),
    ]
