# Generated by Django 3.2.19 on 2023-09-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_barang_transaksi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaksi',
            new_name='Item',
        ),
    ]
