# Generated by Django 4.2.5 on 2023-09-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_item_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
