# Generated by Django 4.2.5 on 2023-09-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_item_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name="item",
            name="time_buy",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
